import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms",
  description:
    "The terms of using Unvibe during its beta, including AI limitations and the absence of any security guarantee.",
};

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of use"
      updated="September 2026"
      intro="Plain-language terms for using Unvibe during its beta. Using the product means you agree to these. This is a summary and may be superseded by a full agreement as the product matures."
    >
      <LegalSection heading="The service">
        <p>
          Unvibe is a desktop application that generates explanations of code to help you
          learn. It is a learning aid, not a code generator, a security scanner, or
          professional advice.
        </p>
      </LegalSection>

      <LegalSection heading="Your responsibilities">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            You are responsible for the code you choose to submit and for having the
            right to submit it to a third-party AI provider.
          </li>
          <li>
            Do not submit code you are contractually or legally prohibited from sharing.
          </li>
          <li>You are responsible for activity under your account and your device.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="AI output can be wrong">
        <p>
          Explanations, comprehension questions, and summaries are generated by AI models
          and <strong>may be inaccurate, incomplete, or outdated</strong>, even when they
          sound confident. Citations are validated against provided context where
          possible but may still be imperfect. Verify anything important against
          authoritative sources. You are responsible for decisions made using AI output.
        </p>
      </LegalSection>

      <LegalSection heading="No security guarantee">
        <p>
          Unvibe does not guarantee that analyzed code is secure, bug-free, or fit for any
          purpose. Any security observations are informational only, not a professional
          audit, and we claim no security certifications.
        </p>
      </LegalSection>

      <LegalSection heading="Beta availability">
        <p>
          The service is provided &quot;as is&quot; and &quot;as available&quot; during
          beta. Features may change or break, and we may modify or discontinue them. We
          will communicate significant changes.
        </p>
      </LegalSection>

      <LegalSection heading="Payments and cancellation">
        <p>
          Free use needs no card. Pro is billed through Stripe, monthly or yearly, and
          renews until you cancel. Pro Lifetime is a one-time payment. You can cancel a
          subscription at any time from the Plan page in the app. Paid access continues
          until the end of the period you already paid for, then your account returns to
          the Free plan. Prices are shown in USD before checkout.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>
          Do not use Unvibe to break the law, to process code you have no right to share,
          to probe or overload our service, or to resell access. Do not try to extract
          other users&apos; data or bypass usage limits. We may suspend accounts that do.
        </p>
      </LegalSection>

      <LegalSection heading="Your content and termination">
        <p>
          You retain ownership of your code. You may stop using the service and{" "}
          <a href="/account-deletion">delete your account</a> at any time. We may suspend
          accounts that violate these terms. To the maximum extent permitted by law, we
          are not liable for indirect or consequential damages or for decisions made in
          reliance on AI output.
        </p>
      </LegalSection>
      <LegalSection heading="Changes and contact">
        <p>
          We may update these terms as the product grows and will change the date above
          when we do. Questions go to{" "}
          <a href="mailto:support@unvibe.site">support@unvibe.site</a>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
