/**
 * FAQ content.
 *
 * Answers match the product as actually scoped:
 * Mac first; selection based (not screen OCR); no local-only mode yet;
 * no enterprise certifications; AI explanations can be wrong.
 */

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  category: "product" | "privacy" | "platform" | "pricing";
}

export const faqCategories: Record<FaqItem["category"], string> = {
  product: "Product",
  privacy: "Privacy & data",
  platform: "Platforms",
  pricing: "Access & pricing",
};

export const faqItems: FaqItem[] = [
  {
    id: "what-is-it",
    question: "What is Unvibe?",
    answer:
      "Unvibe is a desktop AI learning layer for code. It lives beside your editor: select code, choose a depth, and get an explanation that stays open while you work. It also helps you save notes, track concepts, and turn real projects into study material. It is not a course platform or another chat window.",
    category: "product",
  },
  {
    id: "generator",
    question: "Is Unvibe a code generator?",
    answer:
      "No. Unvibe does not write features for you. AI agents can write the code; Unvibe helps you understand, review, and remember it.",
    category: "product",
  },
  {
    id: "editors",
    question: "Which applications will it support?",
    answer:
      "The Mac app is designed to work beside tools you already use, including Cursor, VS Code, GitHub, Claude Code, Terminal, and other editors where you can select code. Some integrations are still planned or in development and are labeled that way on the site.",
    category: "platform",
  },
  {
    id: "screen",
    question: "Does it read my entire screen?",
    answer:
      "No. Unvibe activates intentionally. You choose what to review — a selection, file, diff, or project scope. It does not record your screen or use OCR to watch everything you do.",
    category: "privacy",
  },
  {
    id: "sent",
    question: "What code is sent to AI providers?",
    answer:
      "Only the filtered context you approve for an explanation: typically the selection plus limited surrounding context. Secrets are scanned on your machine first. Default exclusions cover .env files, keys, node_modules, and build output. Your whole repository is never uploaded.",
    category: "privacy",
  },
  {
    id: "levels",
    question: "Can I choose the explanation level?",
    answer:
      "Yes. Depths include First time, Beginner, Intermediate, Advanced, and Expert. The same code can be explained with analogies, syntax walkthroughs, patterns, architecture, or implementation tradeoffs.",
    category: "product",
  },
  {
    id: "repo",
    question: "Can it explain an entire repository?",
    answer:
      "Yes at a summary level. You can move from a line to a function, file, folder, git change, or repository overview. Repo summaries describe modules, data flow, and concepts to learn — they do not dump the entire codebase to a model.",
    category: "product",
  },
  {
    id: "local-mode",
    question: "Is there a local-only mode?",
    answer:
      "Not yet. Explanations are generated by a cloud AI provider after on-device secret filtering and your consent. A fully offline local-model mode is not part of the current release.",
    category: "privacy",
  },
  {
    id: "training",
    question: "Will my private code be used for training?",
    answer:
      "Unvibe does not build its own training dataset from your repositories. Before cloud beta access, we will name the configured provider and disclose its applicable retention and data-use terms; do not treat a secret filter as a guarantee that every sensitive value will be found.",
    category: "privacy",
  },
  {
    id: "free",
    question: "Is Free actually usable?",
    answer:
      "Yes. Free includes the main code-explanation experience with usage and project limits. It is intended to let you experience the real product before paying. No credit card or separate AI API key is required.",
    category: "pricing",
  },
  {
    id: "pro-annual",
    question: "Is Pro cheaper annually?",
    answer: "Yes. Monthly Pro is $8 per month. Annual Pro is $72 per year — about $6 per month, a 25% savings versus paying monthly.",
    category: "pricing",
  },
  {
    id: "cancel",
    question: "What happens if I cancel?",
    answer: "Paid access continues until the end of the current billing period unless otherwise stated during cancellation. Your saved content is handled according to the product retention policy.",
    category: "pricing",
  },
  {
    id: "beta",
    question: "How do I get the product?",
    answer:
      "Join the waitlist on this site, then email preston@unvibe.site and ask for private beta access. Access is invite-only while we keep the beta controlled.",
    category: "pricing",
  },
  {
    id: "windows",
    question: "Is Windows supported?",
    answer:
      "Not yet. Unvibe is Mac-first. You can still join the waitlist from Windows and note your platform in the optional message so we know demand.",
    category: "platform",
  },
  {
    id: "teams",
    question: "Can educators or teams use it?",
    answer:
      "Right now Unvibe is Free and Pro for individuals. Shared team workspaces are paused; each person can use their own Pro account. Join the waitlist if you want to hear when Teams returns.",
    category: "platform",
  },
  {
    id: "delete",
    question: "Can I delete my account and data?",
    answer:
      "Yes. You can disconnect repositories and delete your account and stored learning data. See Account deletion and Data controls for the process.",
    category: "privacy",
  },
  {
    id: "accuracy",
    question: "Can the explanations be wrong?",
    answer:
      "Yes. AI output can be inaccurate even when it sounds confident. Unvibe cites the code it is describing so you can verify it, and comprehension checks help you notice when something does not add up.",
    category: "product",
  },
];
