/**
 * FAQ content.
 *
 * Answers match the product as actually scoped:
 * Mac and Windows public beta; selection based (not screen OCR); no local-only mode yet;
 * no enterprise certifications; AI explanations can be wrong.
 */

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  category: "product" | "privacy" | "platform" | "pricing";
}

export const faqCategories: Record<FaqItem["category"], string> = {
  product: "Product",
  privacy: "Privacy & data",
  platform: "Platforms",
  pricing: "Access & pricing",
};

export const faqItems: FaqItem[] = [
  {
    id: "what-is-it",
    question: "What is Unvibe?",
    answer:
      "Unvibe is a desktop overlay that explains AI-generated code in place. Select code in Cursor or VS Code, press ⌘U / Ctrl+U, and get a leveled explanation beside your editor. You can save it, follow up, and quiz yourself later. It is not a code generator and not another chat window.",
    category: "product",
  },
  {
    id: "generator",
    question: "Is Unvibe a code generator?",
    answer:
      "No. Unvibe does not write features for you. AI agents can write the code; Unvibe helps you understand, review, and remember it.",
    category: "product",
  },
  {
    id: "vs-cursor",
    question: "Why not just ask the agent to explain itself?",
    answer:
      "Agent chat answers live in that conversation and disappear when you move on. Unvibe opens beside the code, offers five depths, and saves the explanation so you can reopen it, follow up, and take a Test me quiz later. Coding agents answer “can I build this?” Unvibe answers “will I still understand this in three weeks?”",
    category: "product",
  },
  {
    id: "editors",
    question: "Which applications will it support?",
    answer:
      "The Mac app is designed to work beside tools you already use, including Cursor, VS Code, GitHub, Claude Code, Terminal, and other editors where you can select code. Some integrations are still planned or in development and are labeled that way on the site.",
    category: "platform",
  },
  {
    id: "screen",
    question: "Does it read my entire screen?",
    answer:
      "No. Unvibe activates intentionally. You choose what to review: a selection, file, diff, or project scope. It does not record your screen or use OCR to watch everything you do.",
    category: "privacy",
  },
  {
    id: "sent",
    question: "What code is sent to AI providers?",
    answer:
      "Unvibe is not an offline processor. When you request an explanation, the selected code and limited surrounding context you approve leave the machine after a local secret scan. They go to Unvibe’s backend, which calls the configured cloud model (OpenRouter free chat models by default, or Anthropic/Gemini if those keys are set). If you paste your own provider key in Settings, that request stays on your Mac and goes only to your provider. Unvibe does not crawl or upload your whole repository. Default exclusions cover .env files, keys, node_modules, and build output.",
    category: "privacy",
  },
  {
    id: "levels",
    question: "Can I choose the explanation level?",
    answer:
      "Yes. Depths include First time, Beginner, Intermediate, Advanced, and Expert. The same code can be explained with analogies, syntax walkthroughs, patterns, architecture, or implementation tradeoffs.",
    category: "product",
  },
  {
    id: "repo",
    question: "Can it explain an entire repository?",
    answer:
      "Yes at a summary level. You can move from a line to a function, file, folder, git change, or repository overview. Repo summaries describe modules, data flow, and concepts to learn. They do not dump the entire codebase to a model.",
    category: "product",
  },
  {
    id: "local-mode",
    question: "Is there a local-only mode?",
    answer:
      "Not yet. Explanations are generated by a cloud AI provider after on-device secret filtering and your consent. A fully offline local-model mode is not part of the current release.",
    category: "privacy",
  },
  {
    id: "training",
    question: "Will my private code be used for training?",
    answer:
      "Unvibe does not build its own training dataset from your repositories. Explanation requests are handled by the cloud provider configured for the service (OpenRouter by default, or Anthropic/Gemini if those keys are set) and are subject to that provider’s retention and data-use terms. Do not treat a secret filter as a guarantee that every sensitive value will be found.",
    category: "privacy",
  },
  {
    id: "free",
    question: "Is Free actually usable?",
    answer:
      "Yes. Free includes the main selected-code explanation experience, saved learning, and study features. No payment card or separate AI provider key is required.",
    category: "pricing",
  },
  {
    id: "pro-annual",
    question: "How much does Pro cost?",
    answer: "Pro is $10 per month for one developer, or $90 per year. Pro Lifetime is $80 one-time for local and core personal features — buy it from Plan in the Unvibe app. Teams founding-pilot pricing is $8 per seat per month, 2 seat minimum and 20 seat maximum. Enterprise starts at $199 per month.",
    category: "pricing",
  },
  {
    id: "cancel",
    question: "What happens if I cancel?",
    answer: "Paid access continues through the end of the billing period. Your account then returns to the Free plan, subject to the Free plan’s limits.",
    category: "pricing",
  },
  {
    id: "beta",
    question: "How do I get the product?",
    answer:
      "The public beta is available now for Apple silicon Mac and Windows x64. Every install starts with 30 days, 50 AI explanations, and 50 selected-code reviews—no API key or card required. Download the direct .dmg or .exe, or copy the installer command, from unvibe.site. For partnerships, contact preston@unvibe.site.",
    category: "pricing",
  },
  {
    id: "windows",
    question: "Is Windows supported?",
    answer:
      "Yes. Windows x64 is available with the same 30-day beta allowance as Mac: 50 AI explanations and 50 selected-code reviews. Download the portable .exe or install from Windows PowerShell only, not cmd.exe: irm https://unvibe.site/install.ps1 | iex. The app is unsigned, so SmartScreen may warn. Choose More info, then Run anyway. Select code in your editor, then press Ctrl+U. Unvibe copies the selection and explains it beside the editor.",
    category: "platform",
  },
  {
    id: "teams",
    question: "What is Unvibe Teams?",
    answer:
      "Unvibe Teams founding pilot is a shared workspace: invite teammates and see who reviewed or understood which file, concept, and project. Full explanation text stays on each person’s device. GitHub intelligence screens (PR understanding, knowledge-risk) are not shipped yet and stay labeled Pilot or Planned. Paid seat checkout is $8/seat/month for 2–20 seats when Stripe Teams billing is enabled.",
    category: "platform",
  },
  {
    id: "delete",
    question: "Can I delete my account and data?",
    answer:
      "Yes. You can disconnect repositories and delete your account and stored learning data. See Account deletion and Data controls for the process.",
    category: "privacy",
  },
  {
    id: "accuracy",
    question: "Can the explanations be wrong?",
    answer:
      "Yes. AI output can be inaccurate even when it sounds confident. Unvibe cites the code it is describing so you can verify it, and comprehension checks help you notice when something does not add up.",
    category: "product",
  },
];
