import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Privacy",
  description:
    "How Unvibe handles code and learning data during the private beta, including on-device secret filtering and cloud-provider disclosure.",
};

export default function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy"
      updated="July 2026"
      intro="Unvibe is a desktop app that helps you understand code. This page describes what it processes and why, in plain language. It reflects how the product actually behaves. It is a summary, not a substitute for the full policy."
    >
      <LegalSection heading="What Unvibe processes">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Code you choose to review.</strong> When you activate Unvibe on a
            selection, that snippet and the limited surrounding context you approve is
            sent to generate an explanation. Before anything leaves your Mac it is
            scanned on-device for secrets, and detected credentials block or warn first.
          </li>
          <li>
            <strong>Repository metadata</strong> such as file paths, structure, and git
            diffs, only when you explicitly review those scopes. Unvibe does not read
            your repository in the background.
          </li>
          <li>
            <strong>Learning records</strong> — which snippets you reviewed,
            comprehension results, concepts, and streaks.
          </li>
          <li>
            <strong>Account data</strong> — your email for sign-in and an
            authentication token.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="What Unvibe does not do">
        <ul className="list-disc space-y-2 pl-5">
          <li>It does not read your repository without an explicit action from you.</li>
          <li>It does not build its own model-training dataset from your private code.</li>
          <li>It does not log the contents of your private code in analytics.</li>
          <li>It does not perform screen recording, OCR capture, or keylogging.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Secret filtering, before anything is sent">
        <p>
          Every remote request is scanned on your Mac for known credential patterns —
          API keys, tokens, private keys — plus high-entropy strings and{" "}
          <code className="font-mono">KEY=</code> style assignments. A hit blocks the
          request and shows you the file and line so you can redact it or add it to a{" "}
          <code className="font-mono">.unvibeignore</code> file. Files like{" "}
          <code className="font-mono">.env</code>, keys,{" "}
          <code className="font-mono">node_modules</code>, and build output are excluded
          by default, and <code className="font-mono">.gitignore</code> is honored.
        </p>
      </LegalSection>

      <LegalSection heading="Consent and the cloud">
        <p>
          Explanations are generated by a configured cloud AI provider, so the
          filtered snippet you approve is sent over an encrypted connection. Cloud
          analysis begins only after an explicit review action. The exact provider and
          applicable retention/data-use terms will be disclosed before cloud beta access.
          Full payload preview and per-repository controls are still being completed. A
          fully local, no-cloud mode is not available yet.
        </p>
      </LegalSection>

      <LegalSection heading="Storage, security, and your rights">
        <p>
          Learning data lives on your Mac and, when you are signed in, syncs to our
          backend where row-level security is designed to restrict direct reads to your account. Your auth
          token is encrypted at rest using the operating system keychain, and data is
          encrypted in transit. Backend at-rest and backup settings must be verified for
          the selected staging/production infrastructure. You can access and delete your
          data — see <a href="/data-controls">data controls</a> and{" "}
          <a href="/account-deletion">account deletion</a>. We use no advertising
          trackers.
        </p>
      </LegalSection>

      <LegalSection heading="Platforms and scope">
        <p>
          Unvibe is Mac first; Windows and Linux are not available yet. We claim no
          security certifications. Explanations are a learning aid, not a security audit
          — see the <a href="/terms">terms</a> for the AI limitations disclaimer.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
