import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Privacy",
  description:
    "How Unvibe handles code and learning data during the private beta, including on-device secret filtering and cloud-provider disclosure.",
};

export default function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy"
      updated="September 2026"
      intro="Unvibe is a desktop app that helps you understand code. This page describes what it processes and why, in plain language. It reflects how the product actually behaves. It is a summary, not a substitute for the full policy."
    >
      <LegalSection heading="What Unvibe processes">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Code you choose to review.</strong> When you activate Unvibe on a
            selection, that snippet and the limited surrounding context you approve is
            sent to generate an explanation. Before anything leaves your computer it is
            scanned on-device for secrets, and detected credentials block or warn first.
          </li>
          <li>
            <strong>Repository metadata</strong> such as file paths, structure, and git
            diffs, only when you explicitly review those scopes. Unvibe does not read
            your repository in the background.
          </li>
          <li>
            <strong>Learning records:</strong> which snippets you reviewed,
            comprehension results, concepts, and streaks.
          </li>
          <li>
            <strong>Account data:</strong> your email for sign-in and an
            authentication token.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="What Unvibe does not do">
        <ul className="list-disc space-y-2 pl-5">
          <li>It does not read your repository without an explicit action from you.</li>
          <li>It does not build its own model-training dataset from your private code.</li>
          <li>It does not log the contents of your private code in analytics.</li>
          <li>It does not perform screen recording, OCR capture, or keylogging.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Secret filtering, before anything is sent">
        <p>
          Every remote request is scanned on your computer for known credential patterns:
          API keys, tokens, private keys, plus high-entropy strings and{" "}
          <code className="font-mono">KEY=</code> style assignments. A hit blocks the
          request and shows you the file and line so you can redact it or add it to a{" "}
          <code className="font-mono">.unvibeignore</code> file. Files like{" "}
          <code className="font-mono">.env</code>, keys,{" "}
          <code className="font-mono">node_modules</code>, and build output are excluded
          by default, and <code className="font-mono">.gitignore</code> is honored.
        </p>
      </LegalSection>

      <LegalSection heading="Consent and the cloud">
        <p>
          Explanations are generated by a configured cloud AI provider, so the
          filtered snippet you approve is sent over an encrypted connection. Cloud
          analysis begins only after an explicit review action. During the beta,
          explanations are generated by Google Gemini through its paid API, which Google
          states is not used to train its models. If you add your own provider key in
          the app (such as OpenRouter or Anthropic), requests go to that provider under
          its terms instead. Full payload preview and per-repository controls are still
          being completed. A fully local, no-cloud mode is not available yet.
        </p>
      </LegalSection>

      <LegalSection heading="Storage, security, and your rights">
        <p>
          Learning data lives on your computer and, when you are signed in, syncs to our
          backend where row-level security is designed to restrict direct reads to your account. Your auth
          token is encrypted at rest using the operating system keychain, and data is
          encrypted in transit. Backend at-rest and backup settings must be verified for
          the selected staging/production infrastructure. You can access and delete your
          data. See <a href="/data-controls">data controls</a> and{" "}
          <a href="/account-deletion">account deletion</a>. We use no advertising
          trackers.
        </p>
      </LegalSection>

      <LegalSection heading="This website">
        <p>
          unvibe.site uses Mixpanel and PostHog to understand how visitors use the site,
          including page views, clicks, and session replays with form inputs masked. We
          use this to fix confusing pages, not to sell or share your data. The desktop
          app does not send this kind of analytics. If you join a list or request a
          download email, we store your name and email to contact you about Unvibe.
        </p>
      </LegalSection>

      <LegalSection heading="Services we rely on">
        <ul className="list-disc space-y-2 pl-5">
          <li><strong>Google Gemini</strong> generates explanations from the filtered snippet.</li>
          <li><strong>Vercel</strong> hosts the website and API.</li>
          <li><strong>Supabase</strong> stores accounts and synced learning records.</li>
          <li><strong>Stripe</strong> processes payments. Unvibe never sees your full card number.</li>
          <li><strong>Resend</strong> delivers sign-in and product emails.</li>
          <li><strong>GitHub</strong> hosts the installer downloads.</li>
          <li><strong>Mixpanel and PostHog</strong> measure website usage.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Children">
        <p>
          Unvibe is not directed at children under 13, and we do not knowingly collect
          their personal information. If you believe a child has given us data, email us
          and we will delete it.
        </p>
      </LegalSection>

      <LegalSection heading="Changes and contact">
        <p>
          We will update this page when the product changes how it handles data, and note
          the date at the top. Questions or requests go to{" "}
          <a href="mailto:support@unvibe.site">support@unvibe.site</a>.
        </p>
      </LegalSection>

      <LegalSection heading="Platforms and scope">
        <p>
          Unvibe private beta is Mac (Apple silicon) and Windows x64. Linux is not available yet. We claim no
          security certifications. Explanations are a learning aid, not a security audit.
          See the <a href="/terms">terms</a> for the AI limitations disclaimer.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
